### ISSUE TITLE
Plugin is not activated correctly

### ISSUE THREAD

**Issue by TobiasLP** [IllgiLP/WorldEditGlobalizer#1]
ENGLISCH:
Good afternoon,

Here's my problem:
When I type /weg upload it says that I can't execute this command on this server. But I installed the plugin correctly, as you can read on the SpigotMC page.

The only error in the server console is that the plugin is not activated properly.

It would be very nice if you would take care of this problem! ;)
If you have any questions, please do not hesitate to contact me. Plugins, console errors and server version are in the attached file.

Thank you very much and I wish you a nice evening!
TobiasLP

DEUTSCH:
Guten Nachmittag,

Ich habe folgendes Problem:
Wenn ich /weg upload eingebe steht dort, dass ich diesen Befehl nicht auf diesem Server ausführen könne. Ich habe jedoch das Plugin korrekt installiert, wie es auf der SpigotMC Seite zu lesen ist.

In der Serverkonsole kommt nur der Fehler, dass das Plugin nicht ordnungsgemäß aktiviert wird.

Es wäre sehr nett, wenn Sie sich dem Problem mal annehmen würden! ;)
Bei Rückfragen stehe ich Ihnen auch gerne zur Verfügung. Plugins, Konsolenfehler und Serverversion stehen in der angehängten Datei.

Vielen Dank und ich wünsche Ihnen noch einen schönen Abend!
TobiasLP

[Fehler.txt](https://github.com/IllgiLP/WorldEditGlobalizer/files/2922252/Fehler.txt)

**Comment by IllgiLP** [comment]
Your spigot/bukkit/paper version is 1.13.x right? Then you need the version 1.3.2 of my plugin, you use 1.2.1 and that's for mc 1.12.x.

Deutsch:
Du braucht die plugin Version 1.3.2 damit das plugin für die 1.13 funktioniert. 1.2.1 ist für die mc Version 1.12.

^^
