### ISSUE TITLE
Severe TPS Drop issue

### ISSUE THREAD

**Issue by NiNjAiKoToBa** [IllgiLP/WorldEditGlobalizer#10]
Hello,

I've had to temporarilly suspend the usgae of the plugin due to a weird TPS issue that was causing my server to drop from 19TPS to 8TPS.

The following was in my timings report:
https://i.imgur.com/UO3dov2.png

Kind Regards

**Comment by IllgiLP** [comment]
Thank you for reporting this issue.

I've looked at the code and it's not running async. My bad. This will be fixed with the next update.

**Comment by NiNjAiKoToBa** [comment]
Hi,

Sorry to bother, but is there any word on when we might see this update? I'm still unable to use the plugin due to the TPS issues and the older versions have been deleted from the plugin page.

Kind Regards
