### ISSUE TITLE
Unknown custom packet identifier

### ISSUE THREAD

**Issue by adsa562** [IllgiLP/WorldEditGlobalizer#12]
Piugin being spammed in the client log in every second.

Server: Bungeecord #1529 with Paper 1.16.1
Client: Minecraft 1.16.1

Plugin Version:
WorldEditGlobalizer 2.0.2
WorldEdit-bukkit-7.2.0-beta-02

![Screenshot](https://user-images.githubusercontent.com/12174873/89526497-6a285980-d81a-11ea-8041-42ee8f7a72f7.png)

**Comment by IllgiLP** [comment]
Thank you for reporting this. It will be fixed with the next update!
