### ISSUE TITLE
PlotSquared | FastAsyncWE incompatiblity - plot clear/delete command

### ISSUE THREAD

**Issue by Tiippex** [IllgiLP/WorldEditGlobalizer#14]
Hello,

I found an issue which is related due to FAWE, WEG & PlotSquared.
When clearing a plot only Y 0-80 is effected. Everything above stays the same.

I tested that with a setup with only a few plugins:
FastAsyncWorldEdit (WorldEdit), LuckPerms, PlotSquared, ProtocolLib, Vault, WorldEditGlobalizerBukkit*

I can't reproduce this issue with AsyncWE.

Steps to reproduce:
Create a single block stack from bottom to top: 
//Expand vert 
//set stone
/plotsquared clear or /plotsquared delete

Versions:
Paper: git-Paper-584 
WEG: 2.0.3
FAWE: 1.16-653;911d3a0
PlotSquared: 5.13.11-Premium

![image](https://user-images.githubusercontent.com/16509128/114239555-84589f80-9986-11eb-82c0-8296238e44fd.png)
![image](https://user-images.githubusercontent.com/16509128/114239679-a6eab880-9986-11eb-98a7-d16de9dda1c1.png)

**Comment by IllgiLP** [comment]
Hey,

does this problem also occure while WEG is not installed?

**Comment by Tiippex** [comment]
Hey,

no, I can’t reproduce the problem without WEG

**Comment by IllgiLP** [comment]
Are there any errors in the console?

**Comment by Tiippex** [comment]
No

**Comment by Tiippex** [comment]
I think we can close this issue now.

The problem is related to the use-disk option from FAWE.
https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/1088
