### ISSUE TITLE
plugin message channel names is too long

### ISSUE THREAD

**Issue by RedstoneFuture** [IllgiLP/WorldEditGlobalizer#2]
Error by server start.

https://pastebin.com/LrU6vnyS

PaperSpigot 1.12.2 + BungeeCord 1.12.2

**Comment by IllgiLP** [comment]
You are using the wrong version of my plugin. This version you are using is for mc 1.13.x. You need to use version 1.2.1 of my plugin to make it work for mc 1.12.x
