### ISSUE TITLE
Error copying the armorstands

### ISSUE THREAD

**Issue by TobiasLP** [IllgiLP/WorldEditGlobalizer#3]
Good evening,

I'd have another problem with the armor stands. If you copy something with //Copy -e, they will be copied to the other servers, but all stands are oriented north.

Maybe you could take a look if you could fix the bug! ;)
Thank you very much and have a nice Sunday evening!
Tobias

**Comment by IllgiLP** [comment]
Entity teleportations are not supported at the moment, but I'm currently at it to get it working. ^^

IllgiLP

**Comment by IllgiLP** [comment]
Fixed in 643d363 and 2447182
