### ISSUE TITLE
no perms

### ISSUE THREAD

**Issue by privileged8222** [IllgiLP/WorldEditGlobalizer#4]
says i have no permissions even tho im opped and have perm nodes :/

**Comment by IllgiLP** [comment]
The permissions have to be set in BungeeCord.

**Comment by privileged8222** [comment]
how would you do this exactly? ty for the fast response

**Comment by IllgiLP** [comment]
Here can you see, how you can use permissions on BungeeCord:
https://www.spigotmc.org/wiki/bungeecord-configuration-guide/
